begin;

alter table auc_lots
  drop constraint if exists auc_lots_auction_id_fkey;

alter table auc_auctions
  drop constraint if exists auc_auctions_pkey;

insert into auc_auctions (
  id,
  house_id,
  title,
  description,
  url,
  is_live,
  start_time,
  end_time,
  image_url,
  updated_at
)
select
  l.auction_id,
  l.house_id,
  'Auktion ' || l.auction_id::text,
  'Autogenerated placeholder created during auction house scoping migration.',
  null,
  false,
  min(l.start_time),
  max(coalesce(l.local_end_time, l.end_time)),
  max(l.thumbnail_url),
  now()
from auc_lots l
left join auc_auctions a
  on a.house_id = l.house_id
 and a.id = l.auction_id
where l.house_id is not null
  and l.auction_id is not null
  and a.id is null
group by l.house_id, l.auction_id
on conflict (house_id, id) do nothing;

alter table auc_auctions
  add constraint auc_auctions_pkey primary key (house_id, id);

create index if not exists idx_auc_auctions_house_time
  on auc_auctions(house_id, start_time, end_time);

create index if not exists idx_auc_lots_house_auction
  on auc_lots(house_id, auction_id);

alter table auc_lots
  add constraint auc_lots_house_id_auction_id_fkey
  foreign key (house_id, auction_id)
  references auc_auctions(house_id, id)
  on delete cascade;

commit;