import type { AuctionHouse } from "@/lib/types";

/**
 * Feed source registry.
 * Add new auction houses here — the ingester will pick them up automatically.
 * These are also seeded into the auc_auction_houses table on first run.
 */
export const FEED_SOURCES: Omit<AuctionHouse, "active" | "lastSynced">[] = [
  {
    id: "olsens-auktioner",
    name: "Olséns Auktioner",
    feedUrl: "https://www.olsensauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.olsensauktioner.se",
    city: "Norrköping",
    country: "SE",
  },
  {
    id: "ystads-auktioner",
    name: "Ystads Auktioner",
    feedUrl: "https://www.ystadsauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.ystadsauktioner.se",
    city: "Ystad",
    country: "SE",
  },
  {
    id: "knutson-bloom",
    name: "Knutson & Bloom Auktioner",
    feedUrl: "https://www.knutsonbloomauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.knutsonbloomauktioner.se",
    city: "Malmö",
    country: "SE",
  },
  {
    id: "myntauktioner",
    name: "Myntauktioner",
    feedUrl: "https://www.myntauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.myntauktioner.se",
    city: "Stockholm",
    country: "SE",
  },
  {
    id: "dahlstroms-rare-prints",
    name: "Dahlstroms Rare Prints",
    feedUrl:
      "https://auctions.dahlstromsrareprints.com/api/feed?apiVersion=2.0",
    websiteUrl: "https://auctions.dahlstromsrareprints.com",
    city: "Tallinn",
    country: "EE",
  },
  {
    id: "karlssons-auktioner",
    name: "Karlssons Auktioner",
    feedUrl: "https://www.karlssonsauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.karlssonsauktioner.se",
    city: "Trelleborg",
    country: "SE",
  },
  {
    id: "dalarnas-auktionsbyra",
    name: "Dalarnas Auktionsbyra",
    feedUrl: "https://www.dalarnasauktionsbyra.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.dalarnasauktionsbyra.se",
    city: "Borlange",
    country: "SE",
  },
  {
    id: "laholms-auktioner",
    name: "Laholms Handel Auktioner Partier",
    feedUrl: "https://www.laholmsauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.laholmsauktioner.se",
    city: "Laholm",
    country: "SE",
  },
  {
    id: "bergviks-auktionstjanst",
    name: "Bergviks Auktionstjanst",
    feedUrl: "https://www.auktionstjanst.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.auktionstjanst.se",
    city: "Bergvik",
    country: "SE",
  },
  {
    id: "snapphane-auktioner",
    name: "Snapphane Auktioner",
    feedUrl: "https://www.snapphaneauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.snapphaneauktioner.se",
    city: "Hassleholm",
    country: "SE",
  },
  {
    id: "bastionen-auktioner",
    name: "Bastionen Auktioner",
    feedUrl: "https://www.basti.dk/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.basti.dk",
    city: "Vordingborg",
    country: "DK",
  },
  {
    id: "sodersens",
    name: "Södersens Auktionshus",
    feedUrl: "https://sodersens.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://sodersens.se",
    city: "Bålsta",
    country: "SE",
  },
  {
    id: "lp-foto-auktioner",
    name: "LP Foto Auktioner",
    feedUrl: "https://lpfoto.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://lpfoto.se",
    city: "Stockholm",
    country: "SE",
  },
  {
    id: "malmo-frimarkshandel",
    name: "Malmö Frimärkshandel",
    feedUrl: "https://auktion.malmofrimarkshandel.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://auktion.malmofrimarkshandel.se",
    city: "Malmö",
    country: "SE",
  },
  {
    id: "kanonauktioner",
    name: "Kanonauktioner",
    feedUrl: "https://kanonauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://kanonauktioner.se",
    city: "Saltsjö-Boo",
    country: "SE",
  },
  {
    id: "upplands-auktionsverk",
    name: "Upplands Auktionsverk",
    feedUrl: "https://upplandsauktionsverk.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://upplandsauktionsverk.se",
    city: "Uppsala",
    country: "SE",
  },
  {
    id: "malardalens-auktioner",
    name: "Mälardalens Auktioner",
    feedUrl: "https://malardalensauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://malardalensauktioner.se",
    city: "Solna",
    country: "SE",
  },
  {
    id: "karljohan-auktioner",
    name: "Karljohan Auktioner",
    feedUrl: "https://karljohanauktioner.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://karljohanauktioner.se",
    city: "Södra Sandby",
    country: "SE",
  },
  {
    id: "ingelmark",
    name: "Ingelmark Antik och Design",
    feedUrl: "https://ingelmark.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://ingelmark.se",
    city: "Visby",
    country: "SE",
  },
  {
    id: "auktionen-pa-bruket",
    name: "Auktionen på Bruket",
    feedUrl: "https://auktionenpabruket.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://auktionenpabruket.se",
    city: "Österbybruk",
    country: "SE",
  },
  {
    id: "jamtloppan",
    name: "Jämtloppan",
    feedUrl: "https://jamtloppan.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://jamtloppan.se",
    city: "Tandsbyn",
    country: "SE",
  },
  {
    id: "aros-frimarken",
    name: "Aros Frimärken",
    feedUrl: "https://auktion.arosfrimarken.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://auktion.arosfrimarken.se",
    city: "Västerås",
    country: "SE",
  },
  {
    id: "tre-kronor",
    name: "Tre Kronor",
    feedUrl: "https://www.trekronor.one/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.trekronor.one",
    city: "Lindesberg",
    country: "SE",
  },
  {
    id: "conap",
    name: "Conap",
    feedUrl: "https://www.conap.se/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.conap.se/",
    city: "Solna",
    country: "SE",
  },
  {
    id: "haderslev-auktion",
    name: "Haderslev Auktion",
    feedUrl: "https://auktion.haderslevauktion.dk/api/feed?apiVersion=2.0",
    websiteUrl: "https://auktion.haderslevauktion.dk/",
    city: "Haderslev",
    country: "DK",
  },
  {
    id: "wunderkammer",
    name: "Wunderkammer",
    feedUrl: "https://www.wunderkammer.dk/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.wunderkammer.dk/",
    city: "København S",
    country: "DK",
  },
  {
    id: "smb-antikviteter",
    name: "SMB Antikviteter",
    feedUrl: "https://auksjon.smbantikviteter.no/api/feed?apiVersion=2.0",
    websiteUrl: "https://auksjon.smbantikviteter.no/",
    country: "NO",
  },
  {
    id: "auksjoner-no",
    name: "Auksjoner.no",
    feedUrl: "https://www.auksjoner.no/api/feed?apiVersion=2.0",
    websiteUrl: "https://www.auksjoner.no/",
    city: "Lena",
    country: "NO",
  },
  {
    id: "gun-garage-austria",
    name: "Gun Garage Austria",
    feedUrl: "https://auction.gungarage-austria.at/api/feed?apiVersion=2.0",
    websiteUrl: "https://auction.gungarage-austria.at/",
    city: "Spannberg",
    country: "AT",
  },
  // ─── Add more sources below ───
  // {
  //   id: "uppsalaauktion",
  //   name: "Uppsala Auktionskammare",
  //   feedUrl: "https://www.uppsalaauktion.se/api/feed?apiVersion=2.0",
  //   websiteUrl: "https://www.uppsalaauktion.se",
  //   city: "Uppsala",
  //   country: "SE",
  // },
];

/** All known categories across feeds (for facet display order) */
export const CATEGORY_ORDER = [
  "Möbler",
  "Design",
  "Konst",
  "Skulptur",
  "Fotografi",
  "Silver",
  "Smycken",
  "Det dukade bordet",
  "Mattor",
  "Belysning",
  "Glas",
  "Porslin",
  "Keramik",
  "Klockor",
  "Mynt",
  "Frimärken",
  "Militaria",
  "Vapen",
  "Fordon",
  "Elektronik",
  "Verktyg & Maskiner",
  "Musikinstrument",
  "Leksaker",
  "Mode",
  "Asiatika",
  "Retro",
  "Böcker",
  "Diverse",
] as const;

export type KnownCategory = (typeof CATEGORY_ORDER)[number];

/** Swedish cities we know about */
export const KNOWN_CITIES = [
  "Stockholm",
  "Göteborg",
  "Malmö",
  "Uppsala",
  "Solna",
  "Norrköping",
  "Linköping",
  "Helsingborg",
  "Lund",
  "Västerås",
  "Lindesberg",
  "Örebro",
  "Ystad",
  "Trelleborg",
  "Borlänge",
  "Laholm",
  "Bålsta",
  "Södra Sandby",
  "Visby",
  "Österbybruk",
  "Tandsbyn",
  "Hässleholm",
  "Bergvik",
  "Saltsjö-Boo",
  "Haderslev",
  "København S",
  "Lena",
  "Spannberg",
] as const;
